### ISSUE TITLE
Where to report documentation issues?

### ISSUE THREAD

**Issue by soegaard** [processing/processing-website#176]
Hi All,

In the process of "porting" the reference manual and examples of Processing
to a Racket based version of Processing, I have along the way been  reporting 
some issues and made a few pull requests here:

https://github.com/processing/processing-docs/issues

But ... now I discover that the examples are part of `processing-website` too.

Should documentation bugs go here instead?

**Comment by runemadsen** [comment]
Hi @soegaard. Thanks for calling this out! We're in the process of launching an entirely new processing.org website based on code in this repository. We have been working on porting the content from different places to a centralized repo (this), so you are correct that the content is currently duplicated across `processing-website` and `processing-docs`. 

Although this is the new correct place to make those changes, I would encourage you to keep submitting issues to `processing-docs` until the new website it ready. Then we can deprecate `processing-docs` and transfer any outstanding issues to this repo. Since your pull requests have smaller code changes, it will be pretty easy to apply them to this repo too.

Thanks for all the contributions!
