### ISSUE TITLE
Make interactive live sketches for Camera Examples

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-website#313]
The Camera examples should be made interactive with p5.js

- [ ] [Camera/MoveEye](https://processing.org/examples/moveeye.html)
- [ ] [Camera/Orthographic](https://processing.org/examples/orthographic.html)
- [ ] [Camera/Perspective](https://processing.org/examples/perspective.html)

For information on how to make live sketches for examples, please check the [README on examples](https://github.com/processing/processing-website/blob/main/docs/examples.md)

**Comment by trikaphundo** [comment]
> The Camera examples should be made interactive with p5.js

Hello, I thought this was fixed by my PR #309, before filing it I tested the website locally following these [instructions](https://github.com/processing/processing-website#running-the-site-locally), and made sure they all worked. But now I see **none of the new examples in that PR** are working, the website just displays an image instead.

What can possibly have happened? Did I conduct the tests wrongly? Should have I built the website following [these](https://github.com/processing/processing-website/blob/main/docs/examples.md#updating-examples-via-script) instead?

The "liveSketch.js" files are in each of the corresponding examples (for instance [orthographic](https://github.com/processing/processing-website/tree/main/content/examples/Basics/Camera/Orthographic)), but somehow they are not being loaded.

I am very willing to help fix this, and will be thankful to whoever gives me some clue on what to do/try or what did go wrong.

**Comment by SableRaf** [comment]
Hey @trikaphundo. You are absolutely right, that's my bad. I haven't pushed the changes to the live website yet and somehow forgot that this was already fixed in https://github.com/processing/processing-website/pull/309. Closing this.

**Comment by trikaphundo** [comment]
Oh ok, I love good endings :). All examples in PR #309 are now working in the new website release.

I checked [Scrollbar](https://processing.org/examples/scrollbar.html) and [Handles](https://processing.org/examples/handles.html) as well; the P5js sketches of #311 are included and working, unlike their [Processing sketch versions](https://github.com/processing/processing-examples/pull/9) which are not reflected in the Processing code shown in the example pages.

**Comment by SableRaf** [comment]
Was fixed in b33c14b951fad809b17cf6fed49dd26465673c45 thanks for the heads up :)
