### ISSUE TITLE
Profile Picture Icon - not updating 

### ISSUE THREAD

**Issue by kmeis37** [processing/processing-website#466]
after new profile picture uploaded, icon throughout the cite not undated, even though new picture displayed correctly in profile/bio. see images, hopefully they attach

contact: Kelsey (she/her) at kmeis37@gmail.com

![KM_incorrect_profile_pic](https://github.com/processing/processing-website/assets/119521400/09fe89c1-89eb-42ce-a10a-99dabada9c68)
![KM_profile](https://github.com/processing/processing-website/assets/119521400/fb098083-9e05-4c49-83dd-ccec8b665919)

**Comment by SableRaf** [comment]
Hello Kelsey,

Thank you for bringing this to our attention.

Based on the provided details and the screenshot, it appears that the issue is related to OpenProcessing. Just to clarify, the Processing website and the Processing Foundation are not directly affiliated with OpenProcessing.

For resolution, it would be most effective to reach out to OpenProcessing's support directly. Here are the details to assist you:

**Support Email:** info@openprocessing.org
**FAQ:** https://intercom.help/openprocessing/en/
They should be better equipped to address the concern you've faced.

Hope this helps! If you have any other questions or concerns related to the Processing website, feel free to let me know.

Best regards,
Raphaël de Courville
Processing Community Lead

**Comment by kmeis37** [comment]
> 

Thank you Raphaël, I was confused, as you can see, where to report this problem. Thank you for your time.
