### ISSUE TITLE
Text Overflow Issue with Characters in Strings

### ISSUE THREAD

**Issue by Rahulhanje** [processing/processing-website#544]
@SableRaf 
I have encountered an issue where entering a string of text that exceeds the dimensions of the canvas results in the text being cut off or becoming unreadable. The problem arises when the length of the string surpasses the available canvas size.

example URL:https://processing.org/examples/charactersstrings.html

![Screenshot 2024-08-08 150801](https://github.com/user-attachments/assets/a1d0a5f9-8ad8-4a9e-af3b-4f8d29514fd6)

I’d like to work on this issue. Could @SableRaf please assign it to me? Also, I would appreciate any guidance on how to fix it.

**Comment by SableRaf** [comment]
Hi @Rahulhanje,

Good catch! You are correct. The behavior of the live sketch does not match the behavior of the Processing code on the page. This is due to a discrepancy between the way that Processing and p5.js handle text wrapping.

In Processing, it is sufficient to call `text(words, 50, 120, 540, 300);` where the numbers define the boundaries of a rectangle container for the text. Text wrapping is active by default in that scenario.

However, in p5.js, you have to additionally call `textWrap()` to activate the wrapping. In this particular case, this would use the `CHAR` parameter: `textWrap(CHAR)`

To fix this, you will need to edit the corresponding `livesketch.js` file at https://github.com/processing/processing-website/blob/main/content/examples/Basics/Data/CharactersStrings/liveSketch.js

For more details about updating live examples, plese see [examples.md](https://github.com/processing/processing-website/blob/main/docs/examples.md#updating-examples-via-script).

I'll assign this issue to you. Let me know if you still have questions and feel free to make a pull request for the change.

**Comment by SableRaf** [comment]
Correction: the behavior difference is specific to character-wise wrapping. Word wrap DOES work in p5.js by default if you set boundaries for the text rectangle. However it does NOT wrap on characters.

**Comment by Rahulhanje** [comment]
@SableRaf I Created a pull request can you please review the code and merge it

**Comment by Stefterv** [comment]
Hi Rahulhanje,

I took a look at your pull request and have merged it into the website

**Comment by Rahulhanje** [comment]
I checked the website, and my change is visible. It's working perfectly fine

**Comment by SableRaf** [comment]
Hi @Rahulhanje,

Thank you so much and congratulations on your first contribution! 🎉

I reopened this issue to mention that the `livesketch.js` code should replicate the original Processing sketch's behavior as closely as possible. This is important to avoid any confusion for users since the code displayed on the example page is the code of the Processing sketch. I have updated the [documentation about examples](https://github.com/processing/processing-website/blob/main/docs/examples.md) to clarify this point.

Please open a new PR to revert the changes and only leave the `s.textWrap(CHAR)` modification.

Thank you again for your efforts! If you have any questions, feel free to ask.

**Comment by Rahulhanje** [comment]
@SableRaf 
![image](https://github.com/user-attachments/assets/5ed0ce13-72b9-4874-891a-7ec9cbba2f7c)
Sorry to bother you sir , but as mentioned in the documentation, I only edited livesketch.js. If I revert the code, except for 
` s.textWrap(CHAR) `, the error remains the same. If I've misunderstood the error, could you please explain exactly what I need to change in the code?

**Comment by Rahulhanje** [comment]
@SableRaf 
![image](https://github.com/user-attachments/assets/28660568-f908-4a13-a834-e0b9b52b3e50)
I reverted the changes except for s.textWrap(CHAR). Now, the characters vertically overflow the canvas. To fix this, I implemented dynamic height adjustment, but I suspect these code lines are not aligned with the expected behavior of the Processing sketch. Am I right?

**Comment by SableRaf** [comment]
You are correct. The issue was that the text would overflow to the right of the canvas, as shown in your screenshot. Therefore the fix involves wrapping on characters to match the default behavior of Processing. 

The example code featured on the [Character String](https://processing.org/examples/charactersstrings.html) example page doesn't resize the window. Therefore the `livesketch.js` version ported to p5.js should not either.

_Note: I described the character wrapping discrepancy between Processing and p5.js in more detail here: https://github.com/processing/p5.js/issues/7163#issuecomment-2286665351_

![image](https://github.com/user-attachments/assets/b99e582a-0739-4f0d-9194-b39eca1af487)

**Comment by Rahulhanje** [comment]
this means that i shoud not take care of vertical overflow of text right so match the behavior of Processing. am i correct sir

**Comment by SableRaf** [comment]
Correct. The dynamic height adjustment was a clever addition but it doesn't match the Processing sketch so it needs to be removed. Thanks!

**Comment by Rahulhanje** [comment]
Ok sir thankyou for confirming i will make change and create a another pull request 

I also noticed some typos below. Are those `<br/>` tags required? to display on screen 
"[image](https://github.com/user-attachments/assets/a4e8a43b-0fc9-4dc2-99bf-991dbaa83655)

**Comment by SableRaf** [comment]
> I also noticed some typos below. Are those \<br/> tags required? to display on screen

This seems to be an issue on [a small number of examples](https://github.com/search?q=repo%3Aprocessing%2Fprocessing-examples%20%3Cbr%20%2F%3E&type=code). Feel free to open an issue over at the https://github.com/processing/processing-examples/ repository.

**Comment by Rahulhanje** [comment]
Okay, I created a new issue regarding that typo. Is it assignable to me? If possible, I request that it assigned to me.

**Comment by SableRaf** [comment]
Great! Thanks @Rahulhanje 🙏

**Comment by Rahulhanje** [comment]
Welcome sir 
Thankyou for assigning me this issue
