### ISSUE TITLE
Strings no longer immutable?

### ISSUE THREAD

**Issue by twisst** [processing/processing-website#576]
### Select the type of content error.

Factual Mistake

### Section

Tutorials

### Location of the error

https://processing.org/tutorials/text

### Describe the error

Are Strings in Processing still immutable or has that changed? I am by no means an expert Java programmer, but the section by Dan on Strings being immutable (dated 2008) seems to be no longer true. I can do this no problem:

String message = "bleep bloop";
message = message.toUpperCase();
println(message);  // BLEEP BLOOP

### Suggested correction

Simply replace the paragraphs below by:

The method toUpperCase() returns a copy of the String object with all caps. If you want the original String to be changed to all-caps, then assign the result to message:

`String message = "bleep bloop";
message = message.toUpperCase();
println(message);  // BLEEP BLOOP`

### Language

English

### Screenshots or references

Current paragraphs:
"You might notice something a bit odd here. Why didn't we simply say message.toUpperCase() and then print message variable? Instead, we assigned the result of message.toUpperCase() to a new variable with a different name—uppercase.

This is because a String is a special kind of object. It is immutable. An immutable object is one whose data can never be changed. Once we create a String, it stays the same for life. Anytime we want to change the String, we have to create a new one. So in the case of converting to uppercase, the method toUpperCase() returns a copy of the String object with all caps."

**Comment by SableRaf** [comment]
Hi @twisst and thank you for bringing this up! You're correct that the example works because the result of `toUpperCase()` is reassigned to the variable `message`, but this doesn't change the fact that `String` objects in Java are immutable.

The sentence in the tutorial:

> Why didn't we simply say `message.toUpperCase()` and then print the `message` variable?

aims to clarify a potential misunderstanding: `.toUpperCase()` does not modify the original `message` directly but instead returns a new `String` object.

That said, the explanation could be updated to make this behavior clearer and avoid confusion.

If you're interested, you can propose a change by creating a pull request to update the tutorial with your suggestion. If you need help with submitting a PR or have questions about the process, feel free to reach out!

**Comment by twisst** [comment]
I am truly terrible with Github, but I think I did it :-)

**Comment by SableRaf** [comment]
Thanks for your PR. You're doing great! We're all learners here ☺️

To avoid introducing too many concepts at once, I'd suggest focusing solely on the immutability of String and how `toUpperCase()` works, leaving the first part unchanged but adding a part about re-assignment to address the potential confusion. 

What would you think of something like this?

## Suggested Update

We can also change a String to all uppercase using the [toUpperCase()](http://processing.org/reference/String_toUpperCase_.html) method ([toLowerCase()](http://processing.org/reference/String_toLowerCase_.html) is also available).

```
    String uppercase = message.toUpperCase();
    println(uppercase);
```

You might notice something a bit odd here. Why didn't we simply say `message.toUpperCase()` and then print `message` variable? Instead, we assigned the result of `message.toUpperCase()` to a new variable with a different name—`uppercase`.

This is because a String is a special kind of object. It is immutable. An immutable object is one whose data can never be changed. Once we create a String, it stays the same for life. Anytime we want to change the String, we have to assign it to a variable. 

So, in the case of converting to uppercase, the method `toUpperCase()` cannot modify the original String in `message`. It only returns a **new copy** of the String object with all caps.

Note that it **is** possible to use the existing variable `message` to store this new String:

```
    message = message.toUpperCase();
```

You might be thinking, "Wait, didn’t you just say Strings are immutable?" Yes, that’s true. The code above doesn’t change the original String. Instead, it updates the `message` variable to **point to the new String object** created by `toUpperCase()`. Without this reassignment (using the `=` operator), the original `message` would remain unchanged.

**Comment by twisst** [comment]
Much better!

**Comment by twisst** [comment]
I couldn't tell you how Github feels exactly like doing my taxes. All this work for such a simple edit... I added a commit to the original PR and I think that's it...?

**Comment by SableRaf** [comment]
I'm sorry you found it so painful, but you did amazing! Thanks for your contribution Jaap ✨

> Side note: I swear this is true, GitHub **can** be fun!... Granted, I may be the kind of person who finds doing my taxes fun too 🙃 But joke aside, please don't let this discourage you from contributing again! If you do struggle with anything, I'll be here to help 💙

**Comment by twisst** [comment]
No problem! 
I'll take your word for it :-) I would like to have a crack at fixing those broken links, so you may see another PR from me soon 😂
